# Generated by Django 3.2.5 on 2022-10-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninja', '0002_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='poweroff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('Off_time', models.TimeField(max_length=100)),
                ('On_time', models.TimeField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninja.user')),
            ],
        ),
    ]
