# Generated by Django 4.1.1 on 2022-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninja", "0003_poweroff"),
    ]

    operations = [
        migrations.CreateModel(
            name="form1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phonenumber", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("complaints", models.TextField()),
            ],
        ),
    ]
