# Generated by Django 4.1.1 on 2022-10-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ninja", "0004_form"),
    ]

    operations = [
        migrations.RenameModel(old_name="form", new_name="form1",),
    ]
