# Generated by Django 4.1.1 on 2022-10-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ninja", "0005_rename_form_form1"),
    ]

    operations = [
        migrations.RemoveField(model_name="form1", name="user",),
    ]
